#!/usr/bin/env node
// Regenerates extensions/omarchy-menu.snippet.jsonc: a "Style > Menu Bar >
// Workspace Style" submenu with one checkable row per Styles.js entry, plus
// toggles for the Pac-Man options, from the same source of truth that feeds
// manifest.json. Run after editing Styles.js.
//
// This file is a fragment, not a standalone menu config: it holds only the
// new keys, meant to be spliced into the user's own
// ~/.config/omarchy/extensions/omarchy-menu.jsonc (see
// tools/install-menu-entries.sh). A plugin cannot register menu rows itself.
"use strict"

const fs = require("fs")
const path = require("path")

const root = path.join(__dirname, "..")
const { styles, glyphChar } = require(path.join(root, "Styles.js"))

const PLUGIN_ID = "io.github.smoothpixels.glyph-workspaces"
const PLUGIN_DIR = `$HOME/.config/omarchy/plugins/${PLUGIN_ID}`
const CURRENT_STYLE = `${PLUGIN_DIR}/tools/current-style.sh`
const CURRENT_SETTING = `${PLUGIN_DIR}/tools/current-setting.sh`

const j = (value) => JSON.stringify(value)
const row = (key, fields) => `  ${j(key)}: {${fields.join(",")}},`

const lines = []
lines.push(row("style.bar.workspaces", [
  `"icon":${j(glyphChar("f0db"))}`,
  `"label":"Workspace Style"`,
  `"description":"Pick how the Glyph Workspaces plugin draws your workspaces"`
]))

for (const s of styles()) {
  lines.push(row(`style.bar.workspaces.${s.id}`, [
    `"icon":${j(glyphChar(s.icon))}`,
    `"label":${j(s.label)}`,
    `"description":${j(s.description)}`,
    `"checked":${j(`[[ "$(${CURRENT_STYLE})" == "${s.id}" ]]`)}`,
    `"action":${j(`omarchy bar set ${PLUGIN_ID} style ${s.id}`)}`
  ]))
}

// Pac-Man's own toggles, as checkable rows that flip the stored value.
const toggles = [
  { key: "eat", icon: "f0765", label: "Eat pellets", fallback: "true" },
  { key: "ghost", icon: "f02a0", label: "Ghost", fallback: "false" },
  { key: "scroll", icon: "f0142", label: "Scroll to switch", fallback: "false" }
]

for (const t of toggles) {
  const current = `$(${CURRENT_SETTING} ${t.key} ${t.fallback})`
  lines.push(row(`style.bar.workspaces.${t.key}`, [
    `"icon":${j(glyphChar(t.icon))}`,
    `"label":${j(t.label)}`,
    `"checked":${j(`[[ "${current}" == "true" ]]`)}`,
    `"action":${j(`omarchy bar set ${PLUGIN_ID} ${t.key} "$([[ "${current}" == "true" ]] && echo false || echo true)"`)}`
  ]))
}

const header = `// Generated by tools/sync-menu.js from Styles.js. Do not edit by hand;
// edit Styles.js and re-run the generator instead.
//
// This is a fragment: the keys below, not a full omarchy-menu.jsonc file.
// Install with tools/install-menu-entries.sh, which splices them into
// ~/.config/omarchy/extensions/omarchy-menu.jsonc.
`

const outPath = path.join(root, "extensions", "omarchy-menu.snippet.jsonc")
fs.mkdirSync(path.dirname(outPath), { recursive: true })
fs.writeFileSync(outPath, header + lines.join("\n") + "\n")
console.log("Wrote " + (lines.length - 1) + " menu rows to extensions/omarchy-menu.snippet.jsonc")
